default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: storage/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: storage/test.sqlite3

production:
  primary:
    <<: *default
    adapter: postgresql
    encoding: unicode
    url: <%= ENV.fetch("DATABASE_URL") %>

  cache:
    <<: *default
    adapter: postgresql
    encoding: unicode
    url: <%= ENV["CACHE_DATABASE_URL"] || ENV.fetch("DATABASE_URL") %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    adapter: postgresql
    encoding: unicode
    url: <%= ENV["QUEUE_DATABASE_URL"] || ENV.fetch("DATABASE_URL") %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    adapter: postgresql
    encoding: unicode
    url: <%= ENV["CABLE_DATABASE_URL"] || ENV.fetch("DATABASE_URL") %>
    migrations_paths: db/cable_migrate